### ISSUE TITLE
Apagar arquivos dbc/dbf/csv depois de salvar no bucket

### ISSUE THREAD

**Issue by VitorPaes** [heber-augusto/devops-pysus-get-files#10]

**Comment by heber-augusto** [comment]
Versão atual do código já contempla esta funcionalidade. :)

A variável de ambiente REM_INTERMEDIATE permite manter ou remover os arquivos intermediários (dbc, dbf, csv) e a integração com google storage foi testada utilizando o utilitário gcsfuse, cuja instalação e utilização, em linux ubuntu está exemplificada nos arquivos [desta pasta](https://github.com/heber-augusto/devops-pysus-get-files/tree/master/examples/google-storage).
