### ISSUE TITLE
Erro em conversão de csv para parquet

### ISSUE THREAD

**Issue by heber-augusto** [heber-augusto/devops-pysus-get-files#20]
O conteúdo de alguns arquivos estão fazendo com que a conversão de csv para parquet falhe. Acredito que tenha relação com a validação da lib pyarrow não permitir valores nulos. Alguns exemplos que facilitam a reprodução do erro:

1. **/SP/2013/04/SIA/PS/PSSP1304.parquet.gzip** gerando o erro:
pyarrow.lib.ArrowInvalid: ('Invalid null value', 'Conversion failed for column ETNIA with type object')

2. **/SP/2014/02/SIA/PA/PASP1402a.parquet.gzip**  gerando o erro:
pyarrow.lib.ArrowInvalid: ('Invalid null value', 'Conversion failed for column PA_ETNIA with type object')

**Comment by heber-augusto** [comment]
@VitorPaes e @hermes-augusto , conseguem me ajudar aqui?

**Comment by hermes-augusto** [comment]
Acredito que esteja solucionado segue [PR](https://github.com/heber-augusto/devops-pysus-get-files/pull/24) @heber-augusto  poderia rodar o processo para validar? Obrigado e desulpee pela demora

**Comment by heber-augusto** [comment]
@hermes-augusto , testei com os dois arquivos e resolveu. Valeu!!! Não tem que pedir desculpa de nada! Tamojunto! :)
