### ISSUE TITLE
Criar tabela de código/nome de cidade/estado para facilitar uso dos dados

### ISSUE THREAD

**Issue by heber-augusto** [heber-augusto/devops-pysus-get-files#28]
O objetivo desta task é criar um arquivo com as seguintes colunas:
 - código da cidade;
 - nome da cidade;
 - sigla do estado.

Sugestão avaliar a utilização da biblioteca [ibge](https://github.com/leogregianin/ibge/), que aparentemente já cria uma camada de abstração para resolver isso.

**Comment by msbrasil** [comment]
Criei um jupyter notebook que faz a coleta dos 3 itens solicitados e código da UF. Poderia conferir? https://github.com/msbrasil/Painel-Rosa---Voluntariado/blob/main/notebooks/cod%20e%20municipios.ipynb
