### ISSUE TITLE
Criar opção para coletar outros tipos de arquivos PA-AR,AQ/SIH/CNES

### ISSUE THREAD

**Issue by VitorPaes** [heber-augusto/devops-pysus-get-files#8]

**Comment by heber-augusto** [comment]
A versão atual do código já contempla coleta de arquivos SIA, CNES e SIH e seus respectivos grupos.

[Este commit](https://github.com/heber-augusto/devops-pysus-get-files/commit/3423a51a670c0b345edf6fd2dfa4f5c10208feed) contém não só um refactoring de código como também a inclusão dos três tipos de arquivos.
