### ISSUE TITLE
Instalar api do google, mapear e direcionar conteúdo do parque.zip para o bucket.

### ISSUE THREAD

**Issue by VitorPaes** [heber-augusto/devops-pysus-get-files#9]

**Comment by heber-augusto** [comment]
A integração com google storage foi testada utilizando o utilitário gcsfuse, cuja instalação e utilização, em linux ubuntu está exemplificada nos arquivos [desta pasta](https://github.com/heber-augusto/devops-pysus-get-files/tree/master/examples/google-storage).

A hierarquia de pastas propostas (ESTADO -> ANO -> MES -> TIPO -> GRUPO>) foi incluída [neste commit](https://github.com/heber-augusto/devops-pysus-get-files/commit/3c1c772752d02e8f0109246a7927382594149947).
